package net.ex337.hotrepart.loadtester.telemetry;

/**
 * The interface that load generators must implement. The LoadReceiver
 * object received reports of generated load.
 * 
 * @author ian
 */
public interface LoadGenerator extends Runnable {

    /**
     *
     * @param receiver the LoadReceiver which collates the load generated by the implementing object.
     */
	public void setLoadReceiver(LoadReceiver receiver);

}
